language: ruby
cache: bundler
before_install:
- sudo apt-get update
- sudo apt-get install libsnappy-dev
- git clone git://github.com/spotify/sparkey.git
- cd sparkey
- autoreconf --install
- ./configure --prefix=/usr
- make
- sudo make install
- cd /home/travis/build/akerl/hammerstore
rvm:
- 2.2.2
- 2.2.1
- 2.2.0
- 2.1.6
- 2.0.0-p598
- 1.9.3-p551
notifications:
  email: false
  irc:
    channels:
    - irc.oftc.net#akerl
    template:
    - "%{repository}/%{branch}/%{build_number}: %{message} -- %{build_url}"
